### ISSUE TITLE
pods for pega-web, pega-batch etc as pega app is not able to connect to postgres db while trying using helm charts

### ISSUE THREAD

**Issue by a007singh** [pegasystems/pega-helm-charts#174]
Here are the traces:
Downloading database driver: https://jdbc.postgresql.org/download/postgresql-42.2.14.jar
Using JDBC_URL: jdbc:postgresql://7f9de7c3-ed0a-41d3-b929-cc07123af086.brjdfmfw09op3teml03g.databases.appdomain.cloud:30225/pega-base
Loading prlog4j2 from /opt/pega/config/prlog4j2.xml...
Loading prconfig from /opt/pega/config/prconfig.xml...
No context.xml was specified in /opt/pega/config/context.xml.  Generating from templates.
JAVA_OPTS: "-Xms4096m -Xmx7168m -Djava.awt.headless=true -Djava.security.properties=/usr/local/tomcat/conf/java.security.overwrite -DNodeTier=web -XX:HeapDumpPath=/heapdumps -Dpega.logdir=/usr/local/tomcat/logs/pega-web-69c4c6f687-q8vgq"
CATALINA_OPTS: " -DmaxThreads=300 -Didentification.nodeid=pega-web-69c4c6f687-q8vgq -DNodeType=WebUser -DNodeSettings="Pega-IntegrationEngine/EnableRequestorPools=false;" -Dindex.directory= -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9001 -Dcom.sun.management.jmxremote.rmi.port=9001 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -DSMAAutoNodeDiscovery=true -DSMAAutoNodeDiscoveryJMXPort=9001 -DSMAAutoNodeDiscoveryPort=8080 "
NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
06-Aug-2020 10:33:32.632 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/9.0.37
06-Aug-2020 10:33:32.634 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Jun 30 2020 20:09:49 UTC
06-Aug-2020 10:33:32.635 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 9.0.37.0
06-Aug-2020 10:33:32.635 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
06-Aug-2020 10:33:32.635 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            3.10.0-1127.13.1.el7.x86_64
06-Aug-2020 10:33:32.635 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
06-Aug-2020 10:33:32.636 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /opt/java/openjdk
06-Aug-2020 10:33:32.636 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           11.0.8+10
06-Aug-2020 10:33:32.636 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            AdoptOpenJDK
06-Aug-2020 10:33:32.636 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
06-Aug-2020 10:33:32.636 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
06-Aug-2020 10:33:32.640 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
06-Aug-2020 10:33:32.640 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
06-Aug-2020 10:33:32.641 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
06-Aug-2020 10:33:32.641 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
06-Aug-2020 10:33:32.641 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
06-Aug-2020 10:33:32.641 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms4096m
06-Aug-2020 10:33:32.641 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx7168m
06-Aug-2020 10:33:32.641 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.awt.headless=true
06-Aug-2020 10:33:32.642 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.security.properties=/usr/local/tomcat/conf/java.security.overwrite
06-Aug-2020 10:33:32.642 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -DNodeTier=web
06-Aug-2020 10:33:32.642 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:HeapDumpPath=/heapdumps
06-Aug-2020 10:33:32.642 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dpega.logdir=/usr/local/tomcat/logs/pega-web-69c4c6f687-q8vgq
06-Aug-2020 10:33:32.642 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
06-Aug-2020 10:33:32.642 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
06-Aug-2020 10:33:32.643 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
06-Aug-2020 10:33:32.643 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -DmaxThreads=300
06-Aug-2020 10:33:32.643 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Didentification.nodeid=pega-web-69c4c6f687-q8vgq
06-Aug-2020 10:33:32.643 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -DNodeType=WebUser
06-Aug-2020 10:33:32.643 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -DNodeSettings=Pega-IntegrationEngine/EnableRequestorPools=false;
06-Aug-2020 10:33:32.643 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dindex.directory=
06-Aug-2020 10:33:32.644 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote
06-Aug-2020 10:33:32.644 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.port=9001
06-Aug-2020 10:33:32.644 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.rmi.port=9001
06-Aug-2020 10:33:32.644 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
06-Aug-2020 10:33:32.644 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.ssl=false
06-Aug-2020 10:33:32.644 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -DSMAAutoNodeDiscovery=true
06-Aug-2020 10:33:32.644 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -DSMAAutoNodeDiscoveryJMXPort=9001
06-Aug-2020 10:33:32.645 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -DSMAAutoNodeDiscoveryPort=8080
06-Aug-2020 10:33:32.645 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
06-Aug-2020 10:33:32.645 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
06-Aug-2020 10:33:32.645 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
06-Aug-2020 10:33:32.645 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
06-Aug-2020 10:33:32.645 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The Apache Tomcat Native library which allows using OpenSSL was not found on the java.library.path: [/usr/lib:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib]
06-Aug-2020 10:33:32.963 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
06-Aug-2020 10:33:33.000 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [626] milliseconds
06-Aug-2020 10:33:33.083 WARNING [main] org.apache.catalina.users.MemoryUserDatabase.createUser Null or zero length user name specified. The user will be ignored.
06-Aug-2020 10:33:33.084 INFO [main] org.apache.tomcat.util.digester.FactoryCreateRule.begin Error creating object: [Null or zero length user name specified. The user will be ignored.]
06-Aug-2020 10:33:33.087 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
06-Aug-2020 10:33:33.087 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.37]
06-Aug-2020 10:33:33.097 INFO [main] org.apache.catalina.startup.HostConfig.deployDescriptor Deploying deployment descriptor [/usr/local/tomcat/conf/Catalina/localhost/prweb.xml]
06-Aug-2020 10:33:33.128 WARNING [main] org.apache.catalina.startup.HostConfig.deployDescriptor A docBase [/usr/local/tomcat/webapps/prweb] inside the host appBase has been specified, and will be ignored
06-Aug-2020 10:33:33.808 INFO [main] org.apache.tomcat.dbcp.dbcp2.BasicDataSourceFactory.getObjectInstance Name = PRFileStore Ignoring unknown property: value of "Database-based File Access" for "description" property
06-Aug-2020 10:33:33.821 INFO [main] org.apache.tomcat.dbcp.dbcp2.BasicDataSourceFactory.getObjectInstance Name = AdminPegaRULES Ignoring unknown property: value of "PegaRULES Admin datasource" for "description" property
06-Aug-2020 10:33:34.693 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
06-Aug-2020 10:33:34.730 INFO [main] com.pega.pegarules.internal.bootstrap.PRBootstrapDataSource. Loading bootstrap properties from /prbootstrap.properties
06-Aug-2020 10:33:34.732 INFO [main] com.pega.pegarules.internal.bootstrap.SettingReaderJNDI. Could not find java:comp/env/prbootstrap/ in the local JNDI context, skipping prconfig setting lookup
06-Aug-2020 10:33:34.732 INFO [main] com.pega.pegarules.internal.bootstrap.SettingReaderJNDI. Could not find prbootstrap in the local JNDI context, skipping prconfig setting lookup
06-Aug-2020 10:33:34.744 INFO [main] com.pega.pegarules.internal.bootstrap.PRBootstrapDataSource. Bootstrap datatables schema: pega_data
06-Aug-2020 10:33:34.768 INFO [main] com.pega.pegarules.internal.bootstrap.PRBootstrapDataSource. Archive version [0      ]
06-Aug-2020 10:33:34.769 INFO [main] com.pega.pegarules.internal.bootstrap.PRBootstrap. Engine schema defined in allclasses: null
06-Aug-2020 10:33:34.771 INFO [main] com.pega.pegarules.internal.bootstrap.PRBootstrap. Engine classes schema: pega_rules
06-Aug-2020 10:33:34.771 INFO [main] com.pega.pegarules.internal.bootstrap.PRBootstrap. Assembled classes schema: pega_rules
06-Aug-2020 10:33:34.771 INFO [main] com.pega.pegarules.internal.bootstrap.PRBootstrap. prbootstrap.properties merged with prbootstrap entries in Data-Admin-System-Settings
06-Aug-2020 10:33:34.789 INFO [main] com.pega.pegarules.internal.bootstrap.PRBootstrap. Using latest detected engine version:(EngineCodeSetVersion= 08-04-02). To specify a different version, use the setting com.pega.pegarules.bootstrap.codeset.version.Pega-EngineCode in prbootstrap.properties.
06-Aug-2020 10:33:34.792 INFO [main] com.pega.pegarules.internal.bootstrap.PRMiniLoader. Will load phase 2 bootstrap from Pega-EngineCode:08-04-02
06-Aug-2020 10:33:34.809 WARNING [main] com.pega.pegarules.internal.bootstrap.PRMiniLoader. com/pega/pegarules/internal/bootstrap/phase2/PRBootstrapImpl.class could not be loaded from pega_rules.pr_engineclasses for '08-04-02' codeset.
06-Aug-2020 10:33:34.810 WARNING [main] com.pega.pegarules.internal.bootstrap.PRMiniLoader. Could not find file:/usr/local/tomcat/webapps/prweb/WEB-INF/lib/prbootstrap-8.4.2-561.jar
06-Aug-2020 10:33:34.819 INFO [main] com.pega.pegarules.internal.bootstrap.PRBootstrap. 
============ PegaRULES Bootstrap Configuration ============
           Date: Thu Aug 06 10:33:34 GMT 2020
   Java Version: AdoptOpenJDK 11.0.8
  Configuration: file:/usr/local/tomcat/webapps/prweb/WEB-INF/classes/prbootstrap.properties
Pega-EngineCode: 08-04-02
       Database: PostgreSQL 12.3
         Driver: PostgreSQL JDBC Driver 42.2.14

(!) Unable to use given database configuration
(!) Unable to locate classes on filesystem
=============== End Bootstrap Configuration ===============

Unable to load phase 2 bootstrap class: com.pega.pegarules.internal.bootstrap.phase2.PRBootstrapImpl
06-Aug-2020 10:33:34.819 SEVERE [main] com.pega.pegarules.internal.bootstrap.PRBootstrap. Error initializing PRAppLoader
	java.lang.ClassNotFoundException: com.pega.pegarules.internal.bootstrap.phase2.PRBootstrapImpl
		at com.pega.pegarules.internal.bootstrap.PRMiniLoader.loadClass(PRMiniLoader.java:378)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
		at com.pega.pegarules.internal.bootstrap.PRBootstrap.loadPhase2BootstrapClass(PRBootstrap.java:730)
		at com.pega.pegarules.internal.bootstrap.PRBootstrap.checkForStartup(PRBootstrap.java:673)
		at com.pega.pegarules.internal.bootstrap.PRBootstrap.invokeMethodPropagatingThrowable(PRBootstrap.java:424)
		at com.pega.pegarules.boot.internal.extbridge.AppServerBridgeToPega.invokeMethodPropagatingThrowable(AppServerBridgeToPega.java:225)
		at com.pega.pegarules.boot.internal.extbridge.AppServerBridgeToPega.invokeMethod(AppServerBridgeToPega.java:274)
		at com.pega.pegarules.internal.web.servlet.WebAppLifeCycleListenerBoot.contextInitialized(WebAppLifeCycleListenerBoot.java:92)
		at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4678)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5139)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
		at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:631)
		at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1830)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
		at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:526)
		at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:425)
		at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
		at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
		at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
		at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
		at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
		at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.startup.Catalina.start(Catalina.java:738)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
06-Aug-2020 10:33:34.821 SEVERE [main] com.pega.pegarules.boot.internal.extbridge.AppServerBridgeToPega. Problem during method invocation (contextInitialized)
	java.lang.RuntimeException: PRAppLoader was not properly initialized, unable to load class com.pega.pegarules.web.servlet.WebAppLifeCycleListener
		at com.pega.pegarules.internal.bootstrap.PRBootstrap.getImplementationOf(PRBootstrap.java:222)
		at com.pega.pegarules.internal.bootstrap.PRBootstrap.getEntry(PRBootstrap.java:339)
		at com.pega.pegarules.internal.bootstrap.PRBootstrap.getMethod(PRBootstrap.java:319)
		at com.pega.pegarules.internal.bootstrap.PRBootstrap.invokeMethodPropagatingThrowable(PRBootstrap.java:425)
		at com.pega.pegarules.boot.internal.extbridge.AppServerBridgeToPega.invokeMethodPropagatingThrowable(AppServerBridgeToPega.java:225)
		at com.pega.pegarules.boot.internal.extbridge.AppServerBridgeToPega.invokeMethod(AppServerBridgeToPega.java:274)
		at com.pega.pegarules.internal.web.servlet.WebAppLifeCycleListenerBoot.contextInitialized(WebAppLifeCycleListenerBoot.java:92)
		at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4678)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5139)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
		at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:631)
		at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1830)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
		at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:526)
		at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:425)
		at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
		at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
		at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
		at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
		at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
		at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.startup.Catalina.start(Catalina.java:738)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method

**Comment by MadhuriArugula** [comment]
@a007singh I do not see any issue with `pegasystems/pega:8.4.2` or `latest` image. Is this any custom image?

**Comment by a007singh** [comment]
> @a007singh I do not see any issue with `pegasystems/pega:8.4.2` or `latest` image. Is this any custom image?

@MadhuriArugula Thanks for responding. I have been using pega helm chart with pegasystems/pega image and actions.execute as "deploy"
All the pods involved like pega-web, pega-batch, pega-stream are in RUNNING status but readiness probe says "ContainersNotReady"
The issue seems to be the database connectivity although all the required database parameters have been passed and could see them in config map but not reflecting in Configuration: file:/usr/local/tomcat/webapps/prweb/WEB-INF/classes/prbootstrap.properties

**Comment by pega-embate** [comment]
The database configuration would be context.xml not in prbootstrap.properties

**Comment by zitikay** [comment]
@a007singh are you still seeing this issue? Haven't seen any follow up in a while

**Comment by zitikay** [comment]
Please reopen if you're still having issues
