### ISSUE TITLE
java.lang.UnsupportedOperationException: Not supported for client/server mode

### ISSUE THREAD

**Issue by charoensri** [pegasystems/pega-helm-charts#295]
**Describe the bug**
tail -f -n 1000 /usr/local/tomcat/logs/pega-minikube-0/PegaRULES.log
2021-05-28 10:30:47,936 [   PegaRULES-Batch-1] [  STANDARD] [                    ] [     MKTSC2:01.01.01] (     internal.async.AgentQueue) ERROR   - Agent Pega-SearchEngine #0: System-Queue-FTSIncrementalIndexer.pzFTSIncrementalIndexer encountered an execution error. Restarting after delay.
java.lang.UnsupportedOperationException: Not supported for client/server mode
        at com.pega.platform.search.indexmanager.internal.ESIndexAdminHTTP.isQuorumAvailable(ESIndexAdminHTTP.java:296) ~[search.jar:?]
        at com.pega.platform.pegasearch.indexer.internal.DistributedIndexerAgent.checkQuorumForIndex(DistributedIndexerAgent.java:261) ~[pegasearch.jar:?]
        at com.pega.platform.pegasearch.indexer.internal.DistributedIndexerAgent.validateIfIndexingCanProceed(DistributedIndexerAgent.java:249) ~[pegasearch.jar:?]
        at com.pega.platform.pegasearch.indexer.internal.DistributedIndexerAgent.performIndexing(DistributedIndexerAgent.java:124) ~[pegasearch.jar:?]
        at com.pega.pegarules.session.internal.mgmt.Executable.runIncrementalIndexer(Executable.java:12076) ~[prprivate-session.jar:?]
        at com.pegarules.generated.activity.ra_action_pzftsincrementalindexer_d5a57189f42c1af9200f92e0328c352f.step2_circum0(ra_action_pzftsincrementalindexer_d5a57189f42c1af9200f92e0328c352f.java:222) ~[?:?]
        at com.pegarules.generated.activity.ra_action_pzftsincrementalindexer_d5a57189f42c1af9200f92e0328c352f.perform(ra_action_pzftsincrementalindexer_d5a57189f42c1af9200f92e0328c352f.java:93) ~[?:?]
        at com.pega.pegarules.session.internal.mgmt.Executable.doActivity(Executable.java:2835) ~[prprivate-session.jar:?]
        at com.pega.pegarules.session.internal.async.agent.QueueProcessor.runActivity(QueueProcessor.java:795) ~[prprivate-session.jar:?]
        at com.pega.pegarules.session.internal.async.agent.QueueProcessor.execute(QueueProcessor.java:620) ~[prprivate-session.jar:?]
        at com.pega.pegarules.session.internal.async.BatchRequestorTask.run(BatchRequestorTask.java:1167) ~[prprivate-session.jar:?]
        at com.pega.pegarules.session.internal.PRSessionProviderImpl.performTargetActionWithLock(PRSessionProviderImpl.java:1388) ~[prprivate-session.jar:?]
        at com.pega.pegarules.session.internal.PRSessionProviderImpl.doWithRequestorLocked(PRSessionProviderImpl.java:1131) ~[prprivate-session.jar:?]
        at com.pega.pegarules.session.internal.PRSessionProviderImpl.doWithRequestorLocked(PRSessionProviderImpl.java:1012) ~[prprivate-session.jar:?]
        at com.pega.pegarules.session.internal.async.BatchRequestorTask.run(BatchRequestorTask.java:823) ~[prprivate-session.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]

**Server (if applicable, please complete the following information):**
 - OS:  Ubuntu 18.04
 - Environment: DockerDesktop/WSL2
 - Database: PostgreSQL

**Comment by shashikant-koder** [comment]
1. Is all the configured pods are running ? - Like pega-search-0  pega-minikube-0

What is the URL has been used to communicate with search service ?

**Comment by charoensri** [comment]
Yes, the pod running with STS for both search and pega pod.
the url in Pega Search landing page. ie. http://pega-search
Name:         pega-mypega-0
Namespace:    mypega
Priority:     0
Node:         docker-desktop/192.168.65.4
Start Time:   Thu, 10 Jun 2021 19:30:43 +1000
Labels:       app=pega-mypega
              controller-revision-hash=pega-mypega-65d5c6c56
              statefulset.kubernetes.io/pod-name=pega-mypega-0
Annotations:  config-check: 6a6d72e31f6bb4cea2e4ee2b26db98002f226693c2484ea7d323f97c566c47b0
              config-tier-check: a1c5a2c6af658535cf08c94b27164ad6ba88676bb8becb288b75b3eb4d7c14ab
Status:       Running
IP:           10.1.4.154
IPs:
  IP:           10.1.4.154
Controlled By:  StatefulSet/pega-mypega
Init Containers:
  wait-for-pegasearch:
    Container ID:  docker://d9c9679873a3771da50bbf085be0aa1415a45d371d98ee50cbbffb0c1d8cf653
    Image:         busybox:1.31.0
    Image ID:      docker-pullable://busybox@sha256:fe301db49df08c384001ed752dff6d52b4305a73a7f608f21528048e8a08b51e
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      until $(wget -q -S --spider --timeout=2 -O /dev/null http://pega-search); do echo Waiting for search to become live...; sleep 10; done;
The system up and running, but the tons of of this error in the log file.

**Comment by pega-sagas1** [comment]
@pega-kshev Can you please update on this? Is this resolved and can be closed?

**Comment by pega-kshev** [comment]
Pega version 8.6 and above recommended search configuration is using Search and Reporting Service (SRS) instead of deploying elasticsearch. This issue is outdated and appears to be some deployment issue where pegasearch could not be deployed (not enough resources in minikube?).
