### ISSUE TITLE
 java.lang.NoSuchMethodException: com.pega.pegarules.web.impl.WebStandardImpl.doPostInner

### ISSUE THREAD

**Issue by charoensri** [pegasystems/pega-helm-charts#296]
The the recent image (latest) - Pega fails to bootstrap with the error.
24-May-2021 07:11:05.938 SEVERE [http-nio-8080-exec-18] com.pega.pegarules.boot.internal.extbridge.AppServerBridgeToPega. Problem during method invocation (init)
java.lang.RuntimeException: Unable to retrieve method
at com.pega.pegarules.internal.bootstrap.PRBootstrap.getMethod(PRBootstrap.java:316)
at com.pega.pegarules.internal.bootstrap.PRBootstrap.getEntry(PRBootstrap.java:352)
at com.pega.pegarules.internal.bootstrap.PRBootstrap.getMethod(PRBootstrap.java:322)
at com.pega.pegarules.internal.bootstrap.PRBootstrap.invokeMethodPropagatingThrowable(PRBootstrap.java:428)
at com.pega.pegarules.boot.internal.extbridge.AppServerBridgeToPega.invokeMethodPropagatingThrowable(AppServerBridgeToPega.java:225)
at com.pega.pegarules.boot.internal.extbridge.AppServerBridgeToPega.invokeMethod(AppServerBridgeToPega.java:274)
at com.pega.pegarules.internal.web.servlet.WebStandardBoot.init(WebStandardBoot.java:110)
at javax.servlet.GenericServlet.init(GenericServlet.java:158)
at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1134)
at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1089)
at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:761)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:135)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:764)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NoSuchMethodException: com.pega.pegarules.web.impl.WebStandardImpl.doPostInner(com.pega.pegarules.internal.bootstrap.interfaces.IWebStandard, javax.servlet.http.HttpServletRequest, javax.servlet.http.HttpServletResponse)
at java.base/java.lang.Class.getMethod(Class.java:2108)
at com.pega.pegarules.internal.bootstrap.PRBootstrap.getMethod(PRBootstrap.java:310)
... 28 more

**Comment by MadhuriArugula** [comment]
@charoensri Pega recommends that you specify the absolute image version for the image name like `pegasystems/pega:8.x.y` instead of using the `latest` tag. 
Can you please update your chart to use image tag same as your Pega platform installation version.

**Comment by charoensri** [comment]
I downloaded 8.6.0 and still have the same issue
09-Jun-2021 07:53:48.586 SEVERE [http-nio2-8080-exec-7] com.pega.pegarules.boot.internal.extbridge.AppServerBridgeToPega. Problem during method invocation (init)
        java.lang.RuntimeException: Unable to retrieve method
                at com.pega.pegarules.internal.bootstrap.PRBootstrap.getMethod(PRBootstrap.java:316)
                at com.pega.pegarules.internal.bootstrap.PRBootstrap.getEntry(PRBootstrap.java:352)
                at com.pega.pegarules.internal.bootstrap.PRBootstrap.getMethod(PRBootstrap.java:322)
                at com.pega.pegarules.internal.bootstrap.PRBootstrap.invokeMethodPropagatingThrowable(PRBootstrap.java:428)
                at com.pega.pegarules.boot.internal.extbridge.AppServerBridgeToPega.invokeMethodPropagatingThrowable(AppServerBridgeToPega.java:225)
                at com.pega.pegarules.boot.internal.extbridge.AppServerBridgeToPega.invokeMethod(AppServerBridgeToPega.java:274)
                at com.pega.pegarules.internal.web.servlet.WebStandardBoot.init(WebStandardBoot.java:110)
                at javax.servlet.GenericServlet.init(GenericServlet.java:158)
                at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1134)
                at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1089)
                at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:761)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:135)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
                at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:764)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
                at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1685)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at org.apache.tomcat.util.net.AbstractEndpoint.processSocket(AbstractEndpoint.java:1167)
                at org.apache.tomcat.util.net.Nio2Endpoint.setSocketOptions(Nio2Endpoint.java:331)
                at org.apache.tomcat.util.net.Nio2Endpoint$Nio2Acceptor.completed(Nio2Endpoint.java:451)
                at org.apache.tomcat.util.net.Nio2Endpoint$Nio2Acceptor.completed(Nio2Endpoint.java:387)
                at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
                at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:219)
                at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.base/java.lang.Thread.run(Thread.java:829)
        Caused by: java.lang.NoSuchMethodException: com.pega.pegarules.web.impl.WebStandardImpl.doPostInner(com.pega.pegarules.internal.bootstrap.interfaces.IWebStandard, javax.servlet.http.HttpServletRequest, javax.servlet.http.HttpServletResponse)
                at java.base/java.lang.Class.getMethod(Class.java:2108)
                at com.pega.pegarules.internal.bootstrap.PRBootstrap.getMethod(PRBootstrap.java:310)
                ... 35 more
