### ISSUE TITLE
Helm fails to generate context.xml and server.xml files

### ISSUE THREAD

**Issue by mina-alber** [pegasystems/pega-helm-charts#592]
## Describe the bug

Since the changes introduced to **'charts/pega/config/deploy/context.xml.tmpl'** and **'charts/pega/config/deploy/server.xml.tmpl'** in [PR-570](https://github.com/pegasystems/pega-helm-charts/pull/570) & [PR-572](https://github.com/pegasystems/pega-helm-charts/pull/572), Pega helm installation fails to generate `context.xml` and `server.xml`.

<img width="1244" alt="Screenshot 2023-07-09 at 18 36 16" src="https://github.com/pegasystems/pega-helm-charts/assets/7760329/16537466-95e3-4f68-bf77-ff8901b87666">

```bash
Loading prlog4j2 from /opt/pega/config/prlog4j2.xml...
Loading prconfig from /opt/pega/config/prconfig.xml...
No server.xml was specified in /opt/pega/config/server.xml.  Generating from templates.
No web.xml was specified in /opt/pega/config/web.xml. Using defaults.
No context.xml was specified in /opt/pega/config/context.xml.  Generating from templates.
JAVA_OPTS: "-Xms512m -Xmx6144m -Dpega.logdir=/usr/local/tomcat/logs/pega-batch-98c99966d-t8s24  -Djava.awt.headless=true -Djava.security.properties=/usr/local/tomcat/conf/java.security.overwrite -DNodeTier=batch -XX:HeapDumpPath=/heapdumps --add-modules java.se --add-exports java.base/jd
CATALINA_OPTS: "-Xlog:gc*,gc+heap=debug,gc+humongous=debug:file=/usr/local/tomcat/logs/gc.log:uptime,pid,level,time,tags:filecount=3,filesize=2M -XX:+UseStringDeduplication  -Didentification.nodeid=pega-batch-98c99966d-t8s24 -DNodeType=BackgroundProcessing,Search,Batch,RealTime,BIX -DNod
NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
WARNING: package com.ibm.lang.management.internal not in jdk.management
09-Jul-2023 17:03:23.425 WARNING [main] org.apache.catalina.startup.Catalina.parseServerXml Unable to load server configuration from [/usr/local/tomcat/conf/server.xml]
    java.io.FileNotFoundException: /usr/local/tomcat/conf/server.xml (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
        at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
        at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:184)
        at org.apache.catalina.startup.CatalinaBaseConfigurationSource.getResource(CatalinaBaseConfigurationSource.java:118)
        at org.apache.tomcat.util.file.ConfigurationSource.getConfResource(ConfigurationSource.java:150)
        at org.apache.tomcat.util.file.ConfigurationSource.getServerXml(ConfigurationSource.java:127)
        at org.apache.catalina.startup.CatalinaBaseConfigurationSource.getServerXml(CatalinaBaseConfigurationSource.java:52)
        at org.apache.catalina.startup.Catalina.parseServerXml(Catalina.java:606)
        at org.apache.catalina.startup.Catalina.load(Catalina.java:709)
        at org.apache.catalina.startup.Catalina.load(Catalina.java:746)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:307)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:477)
09-Jul-2023 17:03:23.428 SEVERE [main] org.apache.catalina.startup.Catalina.start Cannot start server, server instance is not configured
```
 
## To Reproduce
Installing Pega using Helm without providing custom context.xml or server.xml files.

## Expected behavior
Pega helm charts generate these files from the provided templates.

## Chart version
Pega charts v2.13.2 or newer.

**Comment by arvasrikanth** [comment]
@mina-alber What does "platform version" refer to? Could you test it with the most recent Docker image and Helm release? The problem might not occur when using the latest charts and image.

**Comment by mina-alber** [comment]
@arvasrikanth 
Sorry, I didn't get your question regarding the "platform version", I can't see it anywhere!

I am facing the same issue deploying Pega Charts v3.1.1 or v3.2.0 with Pega Platform 8.8.2.

**Comment by arvasrikanth** [comment]
@mina-alber You answered my question , platform version of your environment is 8.8.2. Can you pull latest image for 8.8.2 and try deploying. Most likely your deployment is using the already downloaded image and there are some changes recently to this image.

**Comment by zitikay** [comment]
@mina-alber  have you attempt to redownload latest 8.8.2 image and retry? As @arvasrikanth  mentioned, you likely have cached image which is missing required changes to be compatible with this chart version

**Comment by zitikay** [comment]
@mina-alber please try with latest downloaded image. I have attempted to reproduce issue, but unable to because I don't have access to older cached image. Deployed successfully with latest charts. Closing issue because of lack of response + inability to reproduce. You're welcome to reopen if you have downloaded latest image and verified it's still not working with latest charts.

**Comment by mina-alber** [comment]
@arvasrikanth @zitikay 
Thanks for getting back to me! I'll give it a try and get back to you.

**Comment by mina-alber** [comment]
@arvasrikanth @zitikay
Thanks a lot! It works fine with Pega 8.8.2 images!
